### ISSUE TITLE
Support native vertical tabs

### ISSUE THREAD

**Issue by 42willow** [cascadefox/cascade#142]
`about:config`:

- `sidebar.verticalTabs`: `true`
- `sidebar.revamp`: `true`

**Comment by 42willow** [comment]
`.tab-context-line` is what's producing the strange dot artifacts, I assume it is to display the container

**Comment by 42willow** [comment]
https://github.com/user-attachments/assets/d20ed3eb-a21a-43f0-88c4-162e5b5f089e


```css
#sidebar-main {
  width: 58px !important; /* figure out the exact width */
  transition: width 0.3s ease;
}
#sidebar-main:hover {
  width: 200px !important;
}
```
